name: wm_mobile
description: "WorkflowManager Mobile - Gestión de trámites y políticas de negocio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP y almacenamiento
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

  # WebSocket / STOMP
  stomp_dart_client: ^3.0.1

  # Configuración de entorno
  flutter_dotenv: ^5.2.1

  # Utilidades
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_wm.png"
  min_sdk_api_18: true # Optional, default is false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - .env.production
